# Generated by Django 5.2 on 2025-04-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
