# Generated by Django 5.2 on 2025-04-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.BinaryField(),
        ),
    ]
